# Generated by Django 5.1.7 on 2025-03-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('OrderID', 'BookID'), name='unique_order_book')],
            },
        ),
    ]
