# Generated by Django 5.1.7 on 2025-04-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'default_permissions': ('view',), 'permissions': [('can_view_report', 'Có thể xem báo cáo')], 'verbose_name': 'Báo cáo', 'verbose_name_plural': 'Báo cáo'},
        ),
    ]
