# Generated by Django 5.1.7 on 2025-04-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'default_permissions': ('view',), 'permissions': [('can_view_report', 'Xem báo cáo')], 'verbose_name': 'Report', 'verbose_name_plural': 'Report'},
        ),
    ]
