# Generated by Django 5.1.7 on 2025-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_report_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
