# Generated by Django 5.1.7 on 2025-04-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_report', 'Có thể xem báo cáo')]},
        ),
    ]
