# Generated by Django 5.1.7 on 2025-04-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_report_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
