# Generated by Django 5.1.7 on 2025-04-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'verbose_name': 'Báo cáo', 'verbose_name_plural': 'Báo cáo'},
        ),
    ]
