# Generated by Django 5.1.7 on 2025-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imagePath',
            field=models.ImageField(blank=True, default='book_images/default.png', null=True, upload_to='book_images'),
        ),
    ]
