# Generated by Django 5.1.7 on 2025-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_book_imagepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report Inventory',
                'verbose_name_plural': 'Report Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report_Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report Revenue',
                'verbose_name_plural': 'Report Revenue',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
