# Generated by Django 5.1.7 on 2025-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=50)),
                ('SupplierNumber', models.CharField(max_length=15)),
                ('SupplierAddress', models.CharField(max_length=200)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
