# Generated by Django 5.1.7 on 2025-03-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('PromotionID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DiscountPercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('CategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
        ),
    ]
