# Generated by Django 5.1.7 on 2025-03-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSlip',
            fields=[
                ('SlipID', models.AutoField(primary_key=True, serialize=False)),
                ('ImportDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('SupplierID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSlipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('SlipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.importslip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('SlipID', 'BookID'), name='unique_slip_book')],
            },
        ),
    ]
